services:
  mongodb:
    image: mongo:8.0.4-noble
    container_name: mongodb_container
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - .data/mongodb_data:/data/db
    deploy:
      resources:
        limits:
          # Check valid values: https://docs.docker.com/reference/compose-file/extension/#specifying-byte-values
          memory: 1gb

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongodb:27017/
    depends_on:
      - mongodb
    links:
      - mongodb:mongo
    deploy:
      resources:
        limits:
          # Check valid values: https://docs.docker.com/reference/compose-file/extension/#specifying-byte-values
          memory: 1gb

  tika-server:
    image: apache/tika:3.0.0.0-full
    container_name: tika_server
    restart: always
    ports:
      - 9998:9998
    deploy:
      resources:
        limits:
          # Check valid values: https://docs.docker.com/reference/compose-file/extension/#specifying-byte-values
          memory: 1gb